### ISSUE TITLE
MoneyPacket Label/Header

### ISSUE THREAD

**Issue by JulianTosh** [woodser/moneypacket.org#1]
I would like to see the moneypacket uploader or paste importer allow for parsing out of non-essential text. 

Example:

> **MoneyPacket:**{"privateKey":"{\"iv\":\"G3Elj9VtPROOhW74sEM0fA==\",\"v\":1,\"iter\":10000,\"ks\":128,\"ts\":64,\"mode\":\"ccm\",\"adata\":\"\",\"cipher\":\"aes\",\"salt\":\"2qTCjlp9Dtw=\",\"ct\":\"pBNIMBNyAE8q3+cJsh22JRHuXFPvLsW5p3KPza8ZDzB7WMXxRgwY+arXnnvlTJ0w0HVh4z75EV2Iya9T\"}","encryption":"sjcl"}

The uploader/paste importer should be able to extract the moneypacket from all that text without displaying an error to the user.

The end game is that a money packet can contain additional user information on what the file is and how to redeem it.

**Comment by woodser** [comment]
Yeah I agree.  Thanks for the feedback.

**Comment by woodser** [comment]
Users can now add arbitrary notes to the money packet file.  Thanks.
