### ISSUE TITLE
Money packet refuses to forward my bits

### ISSUE THREAD

**Issue by wallclockbuilder** [woodser/moneypacket.org#2]
I created a moneypacket with 21bits.
Money packet won't let me retrieve the funds.

![screen shot 2015-08-08 at 6 43 47 pm](https://cloud.githubusercontent.com/assets/2033945/9151742/5b2c8d3c-3dfd-11e5-9439-15d7d6fd286f.png)

**Comment by wallclockbuilder** [comment]
Problem seems to be that moneypacket is trying to send a fee that is greater than my amount.

**Comment by wallclockbuilder** [comment]
Maybe the fee specification can be dropped and made into an opt-in recommendation instead of requirements. Funds should always be forwarded no matter what.

**Comment by woodser** [comment]
Closing since Bitcoin network requires sufficient fee to transfer funds.  Fee calculation is determined by BitPay's API and amount is considered "dust" (~$.02 at today's prices)
